In [1]:
import pandas as pd

In [2]:
coffee=pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [3]:
coffeedrop=coffee.drop(columns=['Units Sold'])
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [4]:
coffeedrop

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [5]:
coffee['price']=3.99
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   3.99
1      Monday       Latte          15   3.99
2     Tuesday    Espresso          30   3.99
3     Tuesday       Latte          20   3.99
4   Wednesday    Espresso          35   3.99
5   Wednesday       Latte          25   3.99
6    Thursday    Espresso          40   3.99
7    Thursday       Latte          30   3.99
8      Friday    Espresso          45   3.99
9      Friday       Latte          35   3.99
10   Saturday    Espresso          45   3.99
11   Saturday       Latte          35   3.99
12     Sunday    Espresso          45   3.99
13     Sunday       Latte          35   3.99

In [6]:
import numpy as np
coffee['new_price']=np.where(coffee['Coffee Type']=='Espresso',3.99,5.99)
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   3.99       3.99
1      Monday       Latte          15   3.99       5.99
2     Tuesday    Espresso          30   3.99       3.99
3     Tuesday       Latte          20   3.99       5.99
4   Wednesday    Espresso          35   3.99       3.99
5   Wednesday       Latte          25   3.99       5.99
6    Thursday    Espresso          40   3.99       3.99
7    Thursday       Latte          30   3.99       5.99
8      Friday    Espresso          45   3.99       3.99
9      Friday       Latte          35   3.99       5.99
10   Saturday    Espresso          45   3.99       3.99
11   Saturday       Latte          35   3.99       5.99
12     Sunday    Espresso          45   3.99       3.99
13     Sunday       Latte          35   3.99       5.99

In [7]:
coffee.columns

Index(['Day', 'Coffee Type', 'Units Sold', 'price', 'new_price'], dtype='object')

In [8]:
coffee.drop(columns=['price'])

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [9]:
coffee.columns

Index(['Day', 'Coffee Type', 'Units Sold', 'price', 'new_price'], dtype='object')

In [10]:
coffee['Revenue']=coffee['Units Sold']*coffee['new_price']
coffee

          Day Coffee Type  Units Sold  price  new_price  Revenue
0      Monday    Espresso          25   3.99       3.99    99.75
1      Monday       Latte          15   3.99       5.99    89.85
2     Tuesday    Espresso          30   3.99       3.99   119.70
3     Tuesday       Latte          20   3.99       5.99   119.80
4   Wednesday    Espresso          35   3.99       3.99   139.65
5   Wednesday       Latte          25   3.99       5.99   149.75
6    Thursday    Espresso          40   3.99       3.99   159.60
7    Thursday       Latte          30   3.99       5.99   179.70
8      Friday    Espresso          45   3.99       3.99   179.55
9      Friday       Latte          35   3.99       5.99   209.65
10   Saturday    Espresso          45   3.99       3.99   179.55
11   Saturday       Latte          35   3.99       5.99   209.65
12     Sunday    Espresso          45   3.99       3.99   179.55
13     Sunday       Latte          35   3.99       5.99   209.65

In [11]:
coffee.columns

Index(['Day', 'Coffee Type', 'Units Sold', 'price', 'new_price', 'Revenue'], dtype='object')

In [12]:
coffee['Units Sold'].value_counts()

Units Sold
35    4
45    3
25    2
30    2
15    1
20    1
40    1
Name: count, dtype: int64

In [13]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64